apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudpose-deployment
  labels:
    app: cloudpose
  namespace: k8s-a-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudpose
  template:
    metadata:
      labels:
        app: cloudpose
    spec:
      containers:
      - name: api
        image: asad2200/k8s-assignment-1:amd64
        ports:
        - containerPort: 60000
        resources:
          requests:
            cpu: "0.5"
            memory: "512Mi"
          limits:
            cpu: "0.5"
            memory: "512Mi"
