apiVersion: v1
kind: Service
metadata:
  name: cloudpose-service
  namespace: k8s-assignment-ns
spec:
  selector:
    app: cloudpose
  type: NodePort
  ports:
  - port: 60000
    targetPort: 60000
    nodePort: 30000